### ISSUE TITLE
Invalid `state` when adding additional scopes

### ISSUE THREAD

**Issue by derrickleemy** [langleyfoxall/xero-laravel#30]
Hey there,

The default scopes `openid email profile offline_access` works fine.
However, when I try to add new scopes `openid email profile offline_access accounting.transactions accounting.settings.read`, I start getting an exception `Invalid `state`. Request may have been tampered with.`

Any ideas?

**Comment by DivineOmega** [comment]
Hi there @derrickleemy .

Not sure what the problem is there. Could you try the following scope list, which I've tested as working?

`openid email profile offline_access accounting.transactions accounting.settings.read accounting.attachments accounting.contacts.read`

**Comment by derrickleemy** [comment]
Same problem!

**Comment by acirinelli** [comment]
Not sure if this will help anyone, but ran into this same problem and the issue was that I was testing the integration locally using ngrok and when redirecting to an ngrok URL the session value for state was not available, so they never matched. Once I changed the redirect URI in Xero to my local url (not ngrok) it worked fine.

**Comment by dextermb** [comment]
Closed issue as no feedback from author after 16 days. Feel free to re-open if you're still having issues after checking session handling :+1:
